python -u MCULoRA/train_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=a  --gpu=0
python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=t  --gpu=0
python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=v  --gpu=0
python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=at  --gpu=0
python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=av --gpu=0
python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=tv --gpu=0
python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=atv  --gpu=0  > MCULoRA_cmumosei.log 2>&1 &
# python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=atv --stage_epoch=50 --gpu=0
# nohup python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=atv --stage_epoch=50 --gpu=0  > MoMKE_cmumosei.log 2>&1 &
# nohup python -u MCULoRA/train_random_MCULoRA.py --dataset=CMUMOSEI --audio-feature=wav2vec-large-c-UTT --text-feature=deberta-large-4-UTT --video-feature=manet_UTT --seed=66 --batch-size=32 --epoch=200 --lr=0.0001 --hidden=256 --depth=4 --num_heads=2 --drop_rate=0.5 --attn_drop_rate=0.0 --test_condition=atv --stage_epoch=50 --gpu=0